### ISSUE TITLE
Implement the Storage Manager module

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/nexus-geonode#116]
The Storage Manager exposes some atomic operations allowing it to manage any RW operation against the persistent storage. This is an internal component meant to be used primarily by the Uploader and Harvester Services, in order to persist raw data into GeoNode. That module is meant to be an abstraction layer making it possible to plug-in different possible concrete implementations of physical storages. A physical storage might be a local hard disk or a service on the cloud.

Accordingly to the document "[SPC - Nexus Project - Resource and Storage Service Design](https://docs.google.com/document/d/1VYP3gfqkDgHWQcRUNuWIp5JjxGkx5_9iGiVxjuJcKSY/edit#heading=h.yv72cr1rc2)" we need to implement the Storage Manager module as follows:

- [x] Create the Django module
- [x] Create the Abstract classes accordingly to the API specs
- [x] Create a pluggable, concrete implementation based on Django [File storage API](https://docs.djangoproject.com/en/3.2/ref/files/storage/)
- [x] Create a pluggable, concrete implementation based on Django Storages "[Amazon S3](https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html)"
