### ISSUE TITLE
Implement the Resource Manager module

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/nexus-geonode#117]
The Resource Manager exposes some atomic operations allowing it to manage the GeoNode `ResourceBase` models. This is an internal component meant to be used primarily by the Resource Service to manage the publication of `ResourceBases` into GeoNode.

Accordingly to the document "[SPC - Nexus Project - Resource and Storage Service Design](https://docs.google.com/document/d/1VYP3gfqkDgHWQcRUNuWIp5JjxGkx5_9iGiVxjuJcKSY/edit#heading=h.yv72cr1rc2)" we need to implement the Storage Manager module as follows:

- [x] Create the Django module
- [x] Implement the concrete classes allowing to perform the APIs operations as described in the tech specs
- [ ] [Optionally] Create the REST APIs endpoints accordingly and attach them to the async tasks
- [x] Implement the intrerfacing with the final tasks (post save layers, etc.)
