### ISSUE TITLE
Implement the Resource Service

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/nexus-geonode#118]
API Endpoints exposing the Resource Descriptor information and actions that can be performed on a resource.

Every interaction with the Resources from an external actor, should be done through this Service, in order to be sure we keep the state of the Descriptor, raw data and Resource Base on GeoNode consistent.

The other modules are meant to be used internally in order to access low-level operations. The Uploader and Harvester Managers are a sort in the middle. They have access to low level operations too, but, on the other hand, it will be their responsibility also to keep the resources consistency intact.

**NOTE:** If not specified, any call to a single endpoint is meant to be synchronous. That means, as an instance, that when issuing the creation of a Resource Descriptor, I’d expect the endpoint returns only when the operation has fully done and the Resource Descriptor has been successfully created and is available for use.

Accordingly to the document "[SPC - Nexus Project - Resource and Storage Service Design](https://docs.google.com/document/d/1VYP3gfqkDgHWQcRUNuWIp5JjxGkx5_9iGiVxjuJcKSY/edit#heading=h.yv72cr1rc2)" we need to implement the Storage Manager module as follows:

- [ ] Create the Django module
- [ ] Create the Resource Descriptor (RD) model
- [ ] Implement methods allowing to perform CRUD operations on RDs
- [ ] Implement the API Endpoints to interact with RDs and link them to async tasks accordingly
- [ ] Implement the API Endpoints to perform RD Operations as described on "RD Operations" section of the technical document
