### ISSUE TITLE
Client - GeoStory Viewer/Editor

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/nexus-geonode#143]
This Page should contain the GeoStory Viewer and Editor. This is the list of current supported plugins in GeoNode for the GeoStory page:

- OmniBar (container role)
- BurgerMenu (container role)
- GeoStory
- MediaEditor
- GeoStoryEditor
- GeoStoryNavigation
- Notifications
- Save
- SaveAs
- Share

![Geostory Editor](https://user-images.githubusercontent.com/19175505/118143092-44645c80-b40b-11eb-884c-02755f502ca6.png)

Intial requrements:
- [ ] Implement a workflow to retrieve resource data and permissions via GeoNode API (app should listen to changes of primary key layers/:pk)
- [ ] Enable editing tools based on the permissions
- [ ] Create new geostory page

Additional plugins:

- [ ] ViewerLayout plugin: the main plugin layout manager to display component in the page #85
- [ ] BrandNavbar plugin (header of layout): the top navbar component with the logo, search bar and user related links #86
- [ ] ActionNavbar plugin (header of layout): the action bar will replace the standard burger menu of mapstore where the menu item could be used to toggle plugin or to provide links or dropdown #77
- [ ] DetailViewer plugin (column of layout): a plugin similar to the DetailPanel component but with the possibility to edit content inline #92
- [ ] Share plugin: a plugin that allow the user to share de document #93
- [ ] Update (Save plugin)
