### ISSUE TITLE
Client - Common issues Viewer/Editor

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/nexus-geonode#158]
This epic collects some common issues related to all viewer and editors:

- [ ] ViewerLayout plugin: the main plugin layout manager to display component in the page #85
- [ ] BrandNavbar plugin (header of layout): the top navbar component with the logo, search bar and user related links #86
- [ ] ActionNavbar plugin (header of layout): the action bar will replace the standard burger menu of mapstore where the menu item could be used to toggle plugin or to provide links or dropdown #77
- [ ] DetailViewer plugin (column of layout): a plugin similar to the DetailPanel component but with the possibility to edit content inline #92
- [ ] Share plugin: a plugin that allow the user to share de document #93
- [ ] Link to django metadata page template #144
- [ ] Update (Save plugin) #146
- [ ] Clone (Save As plugin) #148
