### ISSUE TITLE
Add to favorites

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#165]
- [ ] A new API v2 endpoint to manage user favorites resources https://github.com/geosolutions-it/nexus-geonode/issues/195
- [ ] A favorite icon will let the authenticated user add the resource to his favorites https://github.com/geosolutions-it/nexus-geonode/issues/196

![image.png](https://images.zenhubusercontent.com/5cd43fb0fe59e12f2130c48a/2bad86b0-0678-42dd-8df6-33ee65487289)

- [ ] A favorites filter will let an authenticated user filter favorites resources  https://github.com/geosolutions-it/nexus-geonode/issues/199

![image.png](https://images.zenhubusercontent.com/5cd43fb0fe59e12f2130c48a/626e7869-414c-475d-972c-3a2b2c5c130f)

**Comment by luorlandini** [comment]
I would like to bring one issue about the third point, favourites filter:
all filters in the form, have same endpoint, and following the query string pattern, so more filters selected work in "AND" 
for example:
"ower resource"
/api/v2/resources?filter{owner.pk}=1000&page=1&page_size=20&filter{metadata_only}=false
"ower resource AND resource_type layer"
/api/v2/resources?filter{resource_type.in}=layer&filter{owner.pk}=1000&page=1&page_size=20&filter{metadata_only}=false


The favourites filter has a dedicated endpoint: 
/api/v2/resources/favorites
so cannot works with other filters, in the same request

My suggestions is , if favorites filter has a dedicated endpoint, we should move it out the filters form, else make it follow the
query string pattern

**Comment by giohappy** [comment]
@luorlandini good point. I think we should change the way the /favorites GET endpoint is implemented. A custom `favorites` boolean filter will be implemented, similar to what we do for the bbox.

**Comment by giohappy** [comment]
@luorlandini favorites filter for resources has been implemented https://github.com/GeoNode/geonode/pull/7627
You can add a boolean "favorites" filter to the resources endpoint now.
