### ISSUE TITLE
[Harvester] - Scheduling 

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#169]
- [ ] Model scheduler configuration
- [ ] Implement a configurable dynamic scheduler
- [ ] Implement scheduler API
