### ISSUE TITLE
[Harvesting] - Abstract models and operations

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#170]
- [ ] General harvesting configuration and models https://github.com/geosolutions-it/nexus-geonode/issues/78
- [ ]  Implement abstract interfaces and logic for resources retrieval (check for new, updated, deleted resources on remote source) https://github.com/geosolutions-it/nexus-geonode/issues/172
- [ ] Implement abstract interfaces and logic for data retrieval (check for new, updated, deleted data on remote source) https://github.com/geosolutions-it/nexus-geonode/issues/173
