### ISSUE TITLE
Adapt legacy pages to the new client (links, header, etc.)

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#250]
- [ ] Remove menus links from header and just add a link back to the resource (metadata editing) or back to home
- [x] Rename layer / layers to dataset / datasets https://github.com/geosolutions-it/nexus-geonode/issues/247
- [x] Change button links to reference the new editors (e.g inside metadata editing, upload, etc., the buttons must link to the new editors instead of the legacy pages) https://github.com/geosolutions-it/nexus-geonode/issues/252
