### ISSUE TITLE
Assorted tasks for the client

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#330]
Tasks
- [x] Change "create new" menu like this: https://github.com/geosolutions-it/nexus-geonode/issues/331
   - Upload Dataset
   - Create Dataset (link to [/createlayer/](https://stable.demo.geonode.org/createlayer/))
   - Upload Document
   - Create Map
   - Create Geostory
- [x] Remove edit icons from detail panel. Simply activate editing of title ot abstract by clicking on the text https://github.com/geosolutions-it/nexus-geonode/issues/332
- [x] Add Delete button to Edit menu for all resource types. It must come after any other edit action and the action should have a red background. Delete action must prompt the user for confirm https://github.com/geosolutions-it/nexus-geonode/issues/333
- [x] Remove card menu (it's not that useful in the end) and turn the title into a link to view the resource editor https://github.com/geosolutions-it/nexus-geonode/issues/334
- [x] Add link to "Remote Services" page (yet to define where to put it) 
- [x] Add "under approval" and "unpublished" labels, both to the cards, preview and detail panel. Show only one of them, with "Under approval" having priority. Use resource `is_approved` and `is_published` attributes https://github.com/geosolutions-it/nexus-geonode/issues/335
![image](https://user-images.githubusercontent.com/571129/125909312-92a3159d-9843-47c7-9961-a0ddc7cd03c4.png)
- [x] Add "full screen" button to editors to open open a full screen view of the contents. For the moment it could use the embedded view https://github.com/geosolutions-it/nexus-geonode/issues/336
- [x] https://github.com/geosolutions-it/nexus-geonode/issues/357
