### ISSUE TITLE
UI enhancements

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#536]
- [x] #552
- [x] #526 
- [x] #531 
- [x] #532 
- [x] #535
- [x] https://github.com/geosolutions-it/nexus-geonode/issues/551
- [x] https://github.com/geosolutions-it/nexus-geonode/issues/557
- [x] https://github.com/geosolutions-it/nexus-geonode/issues/558
- [x] https://github.com/geosolutions-it/nexus-geonode/issues/567
