### ISSUE TITLE
Style Editor improvements

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#537]
- [x] Align Apply / Copy from buttons with the Code editor selection, both for Maps and Datasets
![image](https://user-images.githubusercontent.com/571129/147125029-b8924e77-4562-422e-a826-65cb400cc997.png)
- [x] Harmonize the positioning of the Copy from panel for Maps and Datasets. In this moment it appears centred in the page for Datasets, while it is contextual for Maps (maybe this comes for free with the previous point)
- [x] Remove the spinner from the Apply button and make the Apply button only appear when the style is changed
- [x] Add some spacing between Apply and Copy from buttons
- [x] https://github.com/geosolutions-it/MapStore2/issues/7671
- [x] Remove the zoom to icon and harfmonize the close button with the rest
