### ISSUE TITLE
Client - Editors

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#57]
This are the needed routing to implement for the editors:

- [x] `/viewer/#/document/:pk` viewer or editor with general functionalities for document resource #72
- [x] `/viewer/#/layer/:pk` viewer or editor with general functionalities for dataset resource #73
- [x] `/viewer/#/map/:pk` viewer or editor with general functionalities for map resource #75
- [x] `/viewer/#/geostory/:pk` viewer or editor with general functionalities for geostory app resource #143
- [x] common issues #158

The new implementations should use a single configuration for viewer and editor and show the editor tools only if the user has the required permissions

Note: the rotuing could be changed in developing phase
