### ISSUE TITLE
Client - Filter panel improvements #60

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/nexus-geonode#60]
## Mockup

![Filters panel](https://user-images.githubusercontent.com/19175505/112027932-f84a1980-8b37-11eb-8efd-fe3b7251b6f6.png)

## Requirements

- [ ] Move the current filter panel from the search bar to the list of cards
- [ ] Add a Filter button to open the panel ![image](https://user-images.githubusercontent.com/19175505/112028418-6e4e8080-8b38-11eb-8cb7-88331b6a8507.png)
  - it should show a badge with the number of active filters. We should remove the previous behaviour that all selected filters were listed in the filter menu. If a user want's to see all listed filter they will open the new filter panel.
  - it should be located in the filters menu navbar
- [ ] The filters available should be configurable by the localConfig.json and by default shows following fields: “resource type”, “category”, “keyword”, “author”, “spatial extent”. The configuration should take into account also if a user is authenticated and their role (see the property geoNodeConfiguration and current implementation of other menu items to have a consistent methodology between components)
  - filters should show a badge with the count of filters available
  - default filters should provide an autocomplete
- [ ] A spatial filters with a small  map where selected extent is used as filter
  - base map should be configurable (already supported)
  - style of the bbox filter should be configurable (already supported)
- [ ] A "quick filter" tree (see image below) can be configured inside the localConfig.js. The items will depend on the user role.
- [ ] All filters should be applied to the current url so sharing the page will retain the currently active filters (already supported)
- [ ] Add all related documentation as jsdoc or client/README.md 
- [ ] Add unit tests where needed

![image](https://user-images.githubusercontent.com/571129/112031617-d488d280-8b3b-11eb-82c2-2c1564f008be.png)
