### ISSUE TITLE
Client - Datasets Viewer/Editor

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/nexus-geonode#73]
This page editor should be an updated version of the current layer view and edit page. We should improve the usability of the page making a clear difference between layer and map contextes. Theme and layout must be updated to the new page structure.
The current layer page contains following plugins in the configuration layer_view:
- Toolbar (container role)
- DrawerMenu (container role)
- OmniBar (container role)
- Expander (container role)
- BurgerMenu (container role)
- MapFooter (container role)
- Map 
- BackgroundSelector
- Identify
- TOC (not needed anymore?)
- Settings (not used)
- MapLoading
- Measure
- Print
- ZoomAll
- ZoomIn
- ZoomOut
- Timeline
- Playback
- LayerDownload
- AddLayer (not needed anymore?)
- FilterLayer
- ScaleBox
- FeatureEditor (to replace) Edit data opens a new route layers/{pk}/edit-data
- QueryPanel (to replace) probably the action navbar should provide a toggle to open this panel
- MetadataExplorer - Catalog (not needed anymore?)
- MousePosition
- Search
- GoFull (not used)
- FullScreen
- TOCItemsSettings
- Notifications
- Share
- AddGroup (not needed anymore?)
- StyleEditor (to replace) Edit style opens a new route layers/{pk}/edit-style

We should evaluate a replacement of current plugin with container role with a more custom general layout for this page to manage the position of various components

![image](https://user-images.githubusercontent.com/19175505/114396922-6a91a500-9b9e-11eb-9dae-f548c5fa1ace.png)

Intial requrements:
- [x] Implement a workflow to retrieve resource data and permissions via GeoNode API (app should listen to changes of primary key layers/:pk)
- [x] Enable editing tools based on the permissions

Next steps:
- [x] remove TOC and replace with a component that shows the layer title + legend (TBD) #153
- [x] remove burgermenu in favor of action navbar
  

Additional plugins:

- [x] ViewerLayout plugin: the main plugin layout manager to display component in the page #85
- [x] BrandNavbar plugin (header of layout): the top navbar component with the logo, search bar and user related links #86
- [x] ActionNavbar plugin (header of layout): the action bar will replace the standard burger menu of mapstore where the menu item could be used to toggle plugin or to provide links or dropdown #77
- [x] DetailViewer plugin (column of layout): a plugin similar to the DetailPanel component but with the possibility to edit content inline #92
- [x] Share plugin: a plugin that allow the user to share de document #93
- [x] Link to django metadata page template #144
- [x] Update (Save plugin) https://github.com/geosolutions-it/nexus-geonode/issues/317
- [x] Clone (Save As plugin) https://github.com/geosolutions-it/nexus-geonode/issues/318
- [x] Delete https://github.com/geosolutions-it/nexus-geonode/issues/378
- [x] LayerDownload plugin #150
- [x] Improve Style Editor Layout and UX #151
- [x] Improve Feature Editor Layout and UX #152
