### ISSUE TITLE
Client - Maps Viewer/Editor

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/nexus-geonode#75]
The new maps routes is a replacement of the current map view and map edit templates. The plugins used should be the same as before with the major change of the container layout. 

This are the plugins configured in the map page (map_view and map_edit):
- DrawerMenu (container role)
- Toolbar (container role)
- OmniBar (container role)
- Expander (container role)
- BurgerMenu (container role)
- MapFooter (container role)
- Map
- BackgroundSelector
- Identify
- TOC
- Settings
- MapLoading
- Cookie (not used)
- Measure
- Print
- ZoomAll
- ZoomIn
- ZoomOut
- Timeline
- Playback
- LayerDownload
- AddLayer
- FilterLayer
- ScaleBox
- FeatureEditor
- QueryPanel
- MetadataExplorer
- MousePosition
- Search
- GoFull (not used)
- FullScreen
- TOCItemsSettings
- Widgets
- WidgetsTray
- Save
- SaveAs
- Notifications
- Share
- Swipe
- Locate
- WidgetsBuilder
- AddGroup
- StyleEditor

![image](https://user-images.githubusercontent.com/19175505/114406259-af6e0980-9ba7-11eb-831b-014ab981e014.png)

Intial requrements:

- [x] Implement a workflow to retrieve resource data and permissions via GeoNode API (app should listen to changes of primary key maps/:pk)
- [x] Enable editing tools based on the permissions
- [x] Improve the layout container to be reusable in also in the layers pages
- [x] BurgerMenu will be replaced by the action navbar
- [x] Create new map page workflow #160

Additional plugins:

- [x] ViewerLayout plugin: the main plugin layout manager to display component in the page #85
- [x] BrandNavbar plugin (header of layout): the top navbar component with the logo, search bar and user related links #86
- [x] ActionNavbar plugin (header of layout): the action bar will replace the standard burger menu of mapstore where the menu item could be used to toggle plugin or to provide links or dropdown #77
- [x] DetailViewer plugin (column of layout): a plugin similar to the DetailPanel component but with the possibility to edit content inline #92
- [x] Share plugin: a plugin that allow the user to share de document #93
- [x] Link to django metadata page template #144
- [x] Update (Save plugin) #146
- [x] Clone (Save As plugin) https://github.com/geosolutions-it/nexus-geonode/issues/320
- [x] Delete https://github.com/geosolutions-it/nexus-geonode/issues/379
- [x] LayerDownload plugin #150
- [x] Improve Style Editor Layout and UX #151
- [x] TOC Plugin improvements #154
- [x] GeoNode Catalog Plugin #155
- [x] Layer Settings Plugin #156
