### ISSUE TITLE
Client - Homepage UI/UX improvement

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/nexus-geonode#97]
Improvements needed for the homepage:

- [x] Flickering Search bar in homepage when the resource cards grid is empty or filtered
- [x] Improve layout of filter form
- [x] Fix interaction between filter form and detail panel
- [x] Improve filter form toggle UI
- [x] Brand navbar, action navbar and footer to full width
- [x] Add configurable list of options inside the resource cards
- [x] Replace placeholder filters with actual one in filter form
- [x] Improve mobile/small screen layout
- [ ] ~~Highlight changed filters in filter form~~
